### ISSUE TITLE
The code isn't "heroku ready" 

### ISSUE THREAD

**Issue by Edo78** [mvalipour/telegram-bot-webhook#2]
I have forked this repo and before adapting to my needs I'm working to made it ready to be deployed to heroku. 
Ex.  I'm removing the token from the code putting it in an envelope variable 

If you are interested I can made a pull request once I'm ready

**Comment by Edo78** [comment]
I create the pull request #3

**Comment by volodymyrlut** [comment]
actually @Edo78 did the thing (and made the code a little bit more secure)
thnx

**Comment by mvalipour** [comment]
Apologies it took long for me to come back on this.

The PR is now merged.
