### ISSUE TITLE
Heroku error code=H12

### ISSUE THREAD

**Issue by opiu** [mvalipour/telegram-bot-webhook#4]
Hello I keep getting the following error:
at=error code=H12 desc="Request timeout" method=POST path="/mytokenhere" host=myappname.herokuapp.com request_id=0447825e-543f-42fa-a5b4-d73377ae7710 fwd="149.154.167.204" dyno=web.1 connect=0ms service=30061ms status=503 bytes=0

when I send a message to the bot from Telegram and I believe the webhook is called.

Note: port used on Heroku is random, last time was 32210
I am not using self signed certificate.

Thank you

**Comment by d-ivashchuk** [comment]
Hey @opiu did u figure it out?
