### ISSUE TITLE
heroku polling blog link is not working

### ISSUE THREAD

**Issue by ghost** [mvalipour/telegram-bot-webhook#6]
http://mvalipour.github.io/node.js/2015/11/10/build-telegram-bot-nodejs-heroku/

can you help me I get error when opining this link

**Comment by mvalipour** [comment]
Only thing wrong there is the trailing `/` 😄 

Try: [http://mvalipour.github.io/node.js/2015/11/10/build-telegram-bot-nodejs-heroku](http://mvalipour.github.io/node.js/2015/11/10/build-telegram-bot-nodejs-heroku)
